language: go

go:
  - 1.x.x

script:
  - |
    if [ -z "$TRAVIS_TAG" ]; then
        make all
    else
        BUILD_TAG="$TRAVIS_TAG" make all
    fi
  - >
    if [ "$TRAVIS_BRANCH" = "master" ] || [ ! -z "$TRAVIS_TAG" ]; then
      release_tag="$(cd src/github.com/mholt/caddy/caddy && git describe --tags)" &&
      gem install octokit && lib/github_release.rb --secret "$GITHUB_TOKEN" --repo-slug fnkr/caddy-builds --changelog-file bin/caddy-release.md --tag "$release_tag" --name "${release_tag#v}" &&
      rm bin/caddy-release.md
    fi

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: bin/caddy-*
  skip_cleanup: true
  on:
    tags: true
