language: go

go:
  - 1.x.x

script:
  - make all
  - >
    if [ "$TRAVIS_BRANCH" = "master" ] || [ ! -z "$TRAVIS_TAG" ]; then
      release_tag="weekly-$(go version | awk '{print $3}')-$(cd src/github.com/mholt/caddy/caddy && git rev-parse --short=12 HEAD)" &&
      gem install octokit && lib/github_release.rb --secret "$GITHUB_TOKEN" --repo-slug fnkr/caddy-builds --changelog-file bin/caddy-release.md --tag "$release_tag" &&
      rm bin/caddy-release.md
    fi

deploy:
  provider: releases
  api_key: "$GITHUB_TOKEN"
  file_glob: true
  file: bin/caddy-*
  skip_cleanup: true
  on:
    tags: true
